USE legato_db;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS full_name VARCHAR(150) NOT NULL DEFAULT '' AFTER password_hash,
  ADD COLUMN IF NOT EXISTS nickname VARCHAR(80) NOT NULL DEFAULT '' AFTER full_name,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(30) NOT NULL DEFAULT '' AFTER nickname,
  ADD COLUMN IF NOT EXISTS location VARCHAR(255) NOT NULL DEFAULT '' AFTER phone;
