<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>VIP Packages | LEGATO Events & Productions</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,600&display=swap" rel="stylesheet" /><link rel="stylesheet" href="style.css" />
</head>
<body class="inner-page">
  <header class="navbar"><div class="container nav-content"><a href="index.html" class="brand"><img class="custom-logo" src="Assest/legato1.png" alt="LEGATO Events & Productions" /></a><nav class="nav-links" id="navLinks"><a href="index.html">Home</a><a href="about.html">About Us</a><a class="active" href="packages.html">VIP Packages</a><a href="custom.html">Custom Services</a><a href="contact.html">Contact</a></nav><div class="nav-actions"><a href="custom.html" class="btn btn-gold nav-book">Book An Event</a><a href="login.html" class="nav-login">Log In</a><button class="menu-button" id="menuButton" aria-label="Open menu">☰</button></div></div></header>
  <main><section class="page-hero"><div class="container"><p class="section-label">SIGNATURE EXPERIENCES</p><h1>Choose your <em>moment.</em></h1><p>Complete, high-end production packages designed for seamless execution.</p></div></section><section class="packages-section"><div class="container"><div class="package-grid"><article class="package-card"><p class="package-name">VIP 1</p><h3>The Elite Starter</h3><div class="package-price"><strong>₱49,999</strong><span>Up to 50 Guests</span></div><ul><li>Standard Sound · 2 Speakers, 2 Mics</li><li>24 LED Pars Ambient Lighting</li><li>1 Professional Emcee</li><li>Sound Tech & Program Guidance</li></ul><a href="custom.html" class="btn btn-outline package-button">Select VIP 1</a></article><article class="package-card featured-package"><span class="featured-label">MOST REQUESTED</span><p class="package-name">VIP 2</p><h3>The Prestige Experience</h3><div class="package-price"><strong>₱79,999</strong><span>50–150 Guests</span></div><ul><li>Enhanced Sound · 4–6 Speakers, Mixer</li><li>Moving Heads & LED Wall</li><li>1 Professional Emcee</li><li>Full Event Coordination & Timeline</li><li>Dedicated Vendor Liaison</li></ul><a href="custom.html" class="btn btn-gold package-button">Select VIP 2</a></article><article class="package-card"><p class="package-name">VIP 3</p><h3>The Grand Luxe Production</h3><div class="package-price"><strong>₱179,999</strong><span>150+ Guests</span></div><ul><li>Advanced Line Array & Subwoofers</li><li>Full Stage Lighting + FX</li><li>2 Professional Emcees</li><li>Complete Creative Direction & On-Site Team</li><li>Photo/Video & VIP Concierge</li></ul><a href="custom.html" class="btn btn-outline package-button">Select VIP 3</a></article></div></div></section></main>
  <footer><div class="container footer-grid"><div><a href="index.html" class="brand"><img class="footer-custom-logo" src="Assest/White 2.png" alt="LEGATO Events & Productions" /></a><p class="footer-tagline">Where flawless production meets unforgettable celebration.</p></div><div><p class="footer-title">Explore</p><div class="footer-links"><a href="about.html">About Us</a><a href="packages.html">VIP Packages</a><a href="custom.html">Custom Services</a><a href="login.html">Log In</a></div></div><div><p class="footer-title">Contact</p><div class="footer-links"><span>Dumaguete City, Philippines</span><a href="mailto:info@legatoevents.com">info@legatoevents.com</a><a href="tel:+639000000000">+63 9XX XXX XXXX</a></div></div></div><div class="footer-bottom"><div class="container"><span>© 2026 LEGATO Events & Productions. All Rights Reserved.</span><span>Dumaguete · Negros Oriental</span></div></div></footer><script src="script.js"></script>
</body>
</html>
